import React from "react";
import { Link } from "react-router-dom";
const Home = () => {
  return (
    <div className="dhiwise-navigation">
      <h1>Homepage</h1>
      <p className="headline">
        This project was generated By{" "}
        <a href="https://www.dhiwise.com">Dhiwise</a>. Quickly use below links
        to navigate through all pages.
      </p>
      <ul>
        <li>
          <Link to="/elements">ELEMENTS</Link>
        </li>
        <li>
          <Link to="/cards">Cards</Link>
        </li>
        <li>
          <Link to="/row">Row</Link>
        </li>
        <li>
          <Link to="/cover">COVER</Link>
        </li>
        <li>
          <Link to="/homepage">HOMEPAGE</Link>
        </li>
        <li>
          <Link to="/frame48095563">Frame48095563</Link>
        </li>
        <li>
          <Link to="/productpagedescription">PRODUCTPAGEDESCRIPTION</Link>
        </li>
        <li>
          <Link to="/productpagereviews">PRODUCTPAGEREVIEWS</Link>
        </li>
        <li>
          <Link to="/infopage">INFOPAGE</Link>
        </li>
        <li>
          <Link to="/cartpage">CARTPAGE</Link>
        </li>
        <li>
          <Link to="/cartmodal">CARTMODAL</Link>
        </li>
        <li>
          <Link to="/cardssectionexamplefive">CardssectionexampleFive</Link>
        </li>
        <li>
          <Link to="/cardsone">CardsOne</Link>
        </li>
        <li>
          <Link to="/cardssectionexamplefour">CardssectionexampleFour</Link>
        </li>
        <li>
          <Link to="/cardssectionexampleseven">CardssectionexampleSeven</Link>
        </li>
        <li>
          <Link to="/cardssectionexamplesix">CardssectionexampleSix</Link>
        </li>
        <li>
          <Link to="/cardssectionexampleeight">CardssectionexampleEight</Link>
        </li>
        <li>
          <Link to="/cardssectionexamplesevenone">
            CardssectionexampleSevenOne
          </Link>
        </li>
        <li>
          <Link to="/cardssectionexamplenine">CardssectionexampleNine</Link>
        </li>
        <li>
          <Link to="/desktopclientsthree">DesktopclientsThree</Link>
        </li>
        <li>
          <Link to="/desktopproductcardstwentyfive">
            DesktopproductcardsTwentyFive
          </Link>
        </li>
        <li>
          <Link to="/homepageone">HOMEPAGEOne</Link>
        </li>
      </ul>
    </div>
  );
};
export default Home;
